[package]
name = "maze-algorithms"
version = "0.1.0"
authors = ["CliffS <strohs1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

# termion is for linux, mac_os only
# termion = "1.5.5"
